# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftWebView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftWebView
  pod 'WebViewJavascriptBridge', '~> 6.0'
  pod 'Weibo_SDK', :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"
end
